### ISSUE TITLE
Add documentation on flags for different tools

### ISSUE THREAD

**Issue by arihantbansal** [e-roy/create-web3#6]
### Description

Add descriptive documentation for the different flags and their combinations for choosing between React frontend environments, CSS frameworks and Ethereum development environments.

### Why is this needed?

Simplifies usage of the tool for beginners.

### Proposed Solution or API

Available options:

- --ts or --typescript: Use TypeScript instead of JavaScript.
- --use-npm: Use npm for installing dependencies.
- --use-pnpm: Use pnpm for installing dependencies.

Along these lines

**Comment by e-roy** [comment]
@arihantbansal thank you for the suggestion, I did consider doing this, but wanted to consider future potential options for this project
